services:
  db:
    image: postgres:15
    container_name: chamados_db
    environment:
      POSTGRES_USER: deskdata
      POSTGRES_PASSWORD: deskdata
      POSTGRES_DB: chamados_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: